"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import DailyIframe from "@daily-co/daily-js";
import { Check, Copy, Heart, Loader2, MessageCircle, Mic, PhoneOff, Send, Square, Video, X } from "lucide-react";
import { supabase } from "@/lib/supabase";

type Room={id:string;name?:string;daily_room_url:string;daily_room_name:string;is_active:boolean};
type Message={id:string;room_id:string;sender_name:string;type:"text"|"video"|"audio";content:string;created_at:string};

export default function RoomPage(){
 const {roomId}=useParams<{roomId:string}>(), router=useRouter(), search=useSearchParams();
 const isAdmin=search.get("admin")==="1";
 const [room,setRoom]=useState<Room|null>(null),[loading,setLoading]=useState(true),[messages,setMessages]=useState<Message[]>([]),[text,setText]=useState(""),[status,setStatus]=useState("Preparing your call…"),[participants,setParticipants]=useState(0),[adminPresent,setAdminPresent]=useState(isAdmin),[chat,setChat]=useState(false),[leave,setLeave]=useState(false),[copied,setCopied]=useState(false),[ended,setEnded]=useState(false),[messageText,setMessageText]=useState(""),[recording,setRecording]=useState(false),[blob,setBlob]=useState<Blob|null>(null),[blobUrl,setBlobUrl]=useState<string|null>(null),[blobType,setBlobType]=useState<"audio"|"video">("audio");
 const frame=useRef<any>(null), recorder=useRef<MediaRecorder|null>(null), chunks=useRef<Blob[]>([]), container=useRef<HTMLDivElement>(null);

 const loadMessages=useCallback(async()=>{const r=await fetch(`/api/messages?roomId=${encodeURIComponent(roomId)}`,{cache:"no-store"});if(r.ok)setMessages((await r.json()).messages||[])},[roomId]);
 useEffect(()=>{fetch(`/api/rooms?id=${encodeURIComponent(roomId)}`,{cache:"no-store"}).then(async r=>{if(!r.ok)throw 0;return r.json()}).then(setRoom).catch(()=>setEnded(true)).finally(()=>setLoading(false));loadMessages()},[roomId,loadMessages]);
 useEffect(()=>{const c=supabase.channel(`messages:${roomId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`room_id=eq.${roomId}`},p=>setMessages(v=>v.some(m=>m.id===p.new.id)?v:[...v,p.new as Message])).subscribe();return()=>{void supabase.removeChannel(c)}},[roomId]);

 useEffect(()=>{if(!room||!container.current||frame.current||ended)return;let f:any;
  const start=async()=>{try{setStatus("Joining call…");f=DailyIframe.createFrame(container.current!,{iframeStyle:{width:"100%",height:"100%",border:"0"},showLeaveButton:true,showFullscreenButton:true,activeSpeakerMode:false});frame.current=f;
   const sync=()=>{const p=f.participants()||{}, list=Object.values(p) as any[];setParticipants(list.length);const admin=isAdmin||list.some(x=>x?.userData?.isAdmin===true);setAdminPresent(admin);if(!isAdmin&&!admin&&list.length>0)setLeave(true)};
   f.on("joined-meeting",()=>{setStatus("Connected");sync()});f.on("participant-joined",sync);f.on("participant-left",sync);f.on("left-meeting",()=>router.push("/"));f.on("error",()=>setStatus("Video issue — you can still leave a message."));
   await f.join({url:room.daily_room_url,userName:isAdmin?"Admin":"Guest",userData:{isAdmin}});
  }catch{setStatus("Video could not start — you can leave a message instead.");if(!isAdmin)setLeave(true)}};void start();return()=>{try{f?.destroy()}catch{}frame.current=null}},[room,isAdmin,router,ended]);

 const sendText=async()=>{const content=text.trim();if(!content)return;setText("");await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({roomId,senderName:isAdmin?"Admin":"Guest",type:"text",content})})};
 const startRec=async(type:"audio"|"video")=>{try{const stream=await navigator.mediaDevices.getUserMedia(type==="video"?{audio:true,video:{facingMode:"user",width:{ideal:1280},height:{ideal:720}}}:{audio:true});const mime=type==="video"?(MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm"):"audio/webm";const r=new MediaRecorder(stream,{mimeType:mime});chunks.current=[];setBlob(null);setBlobType(type);setBlobUrl(null);r.ondataavailable=e=>e.data.size&&chunks.current.push(e.data);r.onstop=()=>{const b=new Blob(chunks.current,{type:mime});setBlob(b);setBlobUrl(URL.createObjectURL(b));stream.getTracks().forEach(t=>t.stop())};r.start();recorder.current=r;setRecording(true);setTimeout(()=>{if(r.state==="recording")r.stop();setRecording(false)},15000)}catch{alert("Camera or microphone access was blocked. You can still leave a text message.")}};
 const stopRec=()=>{recorder.current?.stop();setRecording(false)};
 const saveMessage=async()=>{if(!messageText.trim()&&!blob)return;if(messageText.trim())await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({roomId,senderName:"Guest",type:"text",content:messageText.trim()})});if(blob){const fr=new FileReader();const data=await new Promise<string>(ok=>{fr.onload=()=>ok(fr.result as string);fr.readAsDataURL(blob)});await fetch("/api/messages",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({roomId,senderName:"Guest",type:blobType,content:data})})}setMessageText("");setBlob(null);if(blobUrl)URL.revokeObjectURL(blobUrl);setBlobUrl(null);setLeave(false);await loadMessages()};
 const copy=async()=>{await navigator.clipboard.writeText(`${location.origin}/room/${roomId}`);setCopied(true);setTimeout(()=>setCopied(false),1800)};
 const endRoom=async()=>{if(!confirm("End this room for everyone?"))return;const r=await fetch(`/api/rooms/${roomId}/end`,{method:"POST"});if(r.ok){setEnded(true);try{await frame.current?.leave()}catch{}}else alert("Only the room creator can end this room.")};

 if(loading)return <div className="min-h-screen grid place-items-center bg-zinc-950 text-white"><Loader2 className="animate-spin"/></div>;
 if(ended||!room)return <div className="min-h-screen grid place-items-center bg-zinc-950 text-white p-6"><div className="text-center"><Heart className="mx-auto mb-4 text-rose-500" fill="currentColor"/><h1 className="text-2xl font-bold">This room has ended</h1><button onClick={()=>router.push("/")} className="mt-6 px-5 py-3 rounded-xl bg-rose-600">Create a new room</button></div></div>;

 return <main className="h-screen overflow-hidden bg-zinc-950 text-white flex flex-col">
  <header className="h-14 shrink-0 border-b border-zinc-800 bg-zinc-900/95 flex items-center justify-between px-3 sm:px-5"><div><div className="font-semibold">Time With Mom</div><div className="text-xs text-zinc-400">{status} · {participants} {participants===1?"person":"people"}</div></div><div className="flex gap-2">{isAdmin&&<><button onClick={copy} className="px-3 py-2 rounded-lg bg-zinc-800 text-xs flex gap-1.5 items-center">{copied?<Check size={14}/>:<Copy size={14}/>} {copied?"Copied":"Copy link"}</button><button onClick={endRoom} className="px-3 py-2 rounded-lg bg-red-600 text-xs flex gap-1.5 items-center"><PhoneOff size={14}/> End room</button></>}<button onClick={()=>setChat(v=>!v)} className="p-2 rounded-lg bg-zinc-800"><MessageCircle size={18}/></button></div></header>
  <section className="flex-1 min-h-0 flex"><div ref={container} className="flex-1 min-w-0 bg-black"/>
   {chat&&<aside className="w-full sm:w-80 border-l border-zinc-800 bg-zinc-900 flex flex-col absolute sm:relative right-0 top-14 sm:top-0 bottom-0 h-[calc(100vh-3.5rem)] sm:h-auto z-20"><div className="p-4 border-b border-zinc-800 flex justify-between"><b>Messages</b><button className="sm:hidden" onClick={()=>setChat(false)}><X size={18}/></button></div><div className="flex-1 overflow-y-auto p-4 space-y-4">{messages.length?messages.map(m=><div key={m.id}><div className="text-xs text-rose-400">{m.sender_name}</div>{m.type==="audio"?<audio controls src={m.content} className="w-full mt-1"/>:m.type==="video"?<video controls src={m.content} className="w-full rounded-lg mt-1"/>:<p className="text-sm text-zinc-200 break-words">{m.content}</p>}</div>):<p className="text-sm text-zinc-500 text-center py-8">No messages yet.</p>}</div><div className="p-3 border-t border-zinc-800 flex gap-2"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void sendText()} placeholder="Type a message…" className="flex-1 bg-zinc-800 rounded-xl px-3 py-2 text-sm outline-none"/><button onClick={()=>void sendText()} className="p-2 rounded-xl bg-rose-600"><Send size={17}/></button></div></aside>}
  </section>
  {!isAdmin&&!adminPresent&&leave&&<div className="fixed inset-0 z-40 bg-black/70 grid place-items-center p-4"><div className="w-full max-w-md rounded-2xl bg-zinc-900 border border-zinc-700 p-5 space-y-4"><div className="flex justify-between"><div><h2 className="text-xl font-semibold">Leave a message</h2><p className="text-sm text-zinc-400 mt-1">Mom isn’t here right now. Leave something for her to find later.</p></div><button onClick={()=>setLeave(false)}><X/></button></div><textarea value={messageText} onChange={e=>setMessageText(e.target.value)} rows={4} placeholder="Hi Mom…" className="w-full bg-zinc-800 rounded-xl p-3 outline-none"/><div className="flex flex-wrap gap-2">{!recording&&!blobUrl&&<><button onClick={()=>void startRec("audio")} className="px-3 py-2 rounded-xl bg-zinc-800 text-sm flex gap-2 items-center"><Mic size={16}/> Record voice</button><button onClick={()=>void startRec("video")} className="px-3 py-2 rounded-xl bg-zinc-800 text-sm flex gap-2 items-center"><Video size={16}/> Record video</button></>}{recording&&<button onClick={stopRec} className="px-3 py-2 rounded-xl bg-red-600 text-sm flex gap-2 items-center"><Square size={16}/> Stop</button>}{blobUrl&&blobType==="audio"&&<audio controls src={blobUrl} className="w-full"/>}{blobUrl&&blobType==="video"&&<video controls src={blobUrl} className="w-full rounded-xl"/>}</div><button onClick={()=>void saveMessage()} disabled={!messageText.trim()&&!blob} className="w-full py-3 rounded-xl bg-rose-600 disabled:opacity-40 font-semibold">Save message</button><p className="text-xs text-zinc-500 text-center">Recordings are limited to 15 seconds.</p></div></div>}
 </main>
}